#!/bin/sh

# Force silly programs to support XDG base directories instead of littering ~
export NPM_CONFIG_USERCONFIG="${XDG_DATA_HOME:-$HOME/.local/share}/npm/npmrc"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export GRADLE_USER_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"/gradle
export STACK_ROOT="${XDG_DATA_HOME:-$HOME/.local/share}"/stack
export GHCUP_USE_XDG_DIRS=1
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="${XDG_CONFIG_HOME:-$HOME/.config}"/java
export SQLITE_HISTORY="${XDG_STATE_HOME:-$HOME/.local/state}"/sqlite_history
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"/cargo
