#!/bin/sh

# Commonly used folders
DATA="${XDG_DATA_HOME:-$HOME/.local/share}"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"
STATE="${XDG_STATE_HOME:-$HOME/.local/state}"

# Force silly programs to support XDG base directories instead of littering ~
export NPM_CONFIG_USERCONFIG="$DATA"/npm/npmrc"
export GOPATH="$DATA/go"
export GRADLE_USER_HOME="$DATA"/gradle
export STACK_ROOT="$DATA"/stack
export GHCUP_USE_XDG_DIRS=1
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$CONFIG"/java
export SQLITE_HISTORY="$STATE"/sqlite_history
export CARGO_HOME="$DATA"/cargo
export GTK2_RC_FILES="$CONFIG"/gtk-2.0/gtkrc 
