#!/bin/sh

# Commonly used folders
DATA="${XDG_DATA_HOME:-$HOME/.local/share}"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"
STATE="${XDG_STATE_HOME:-$HOME/.local/state}"

# Force silly programs to support XDG base directories instead of littering ~
export NPM_CONFIG_USERCONFIG="$DATA"/npm/npmrc
export GOPATH="$DATA/go"
export GRADLE_USER_HOME="$DATA"/gradle
export STACK_XDG=1
export GHCUP_USE_XDG_DIRS=1
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$CONFIG"/java
export SQLITE_HISTORY="$STATE"/sqlite_history
export CARGO_HOME="$DATA"/cargo
export GTK2_RC_FILES="$CONFIG"/gtk-2.0/gtkrc
export GNUPGHOME="$DATA"/gnupg
export JUPYTER_PLATFORM_DIRS=1
#export PARALLEL_HOME="$CONFIG/parallel"
export WGETRC="$CONFIG/wgetrc"
export PYTHON_HISTORY="$STATE/python_history"

# Add ~/.local/bin to the path
[ -d "$HOME/.local/bin" ] && export PATH="$HOME/.local/bin:$PATH"
